version: '3'
services:
  facade:
    build: ./services/facade
    image: loopback-example-facade/facade
    ports:
      - "3000:80"
    links:
      - account
      - customer
      - transaction
    depends_on:
      - mongo
      - account
      - customer
      - transaction
  customer:
    build: ./services/customer
    image: loopback-example-facade/customer-service
    ports:
      - "3001:80"
    depends_on:
      - mongo
  account:
    build: ./services/account
    image: loopback-example-facade/account-service
    ports:
      - "3002:80"
    depends_on:
      - mongo
  transaction:
    build: ./services/transaction
    image: loopback-example-facade/transaction
    ports:
      - "3003:80"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /usr/local/var/mongodb:/data/db
    ports:
      - "27017:27017"
